class CreateZaikos < ActiveRecord::Migration
  def change
    create_table :zaikos do |t|
      t.string :stock_id, unique: true
      t.string :goocar_id
      t.string :owner_cd
      t.string :n_p_country_nm_n
      t.integer :n_country_cd
      t.string :brand_nm
      t.integer :n_maker_cd
      t.string :n_p_brand_nm_n
      t.integer :n_brand_cd
      t.string :n_p_car_nm_n
      t.integer :n_car_cd
      t.string :n_p_grade_nm_n
      t.string :grade_nm
      t.integer :n_p_grade_id
      t.string :body_nm
      t.integer :n_body_cd
      t.string :exhaust_nm
      t.string :n_p_door_n
      t.string :fukabun
      t.integer :repair_flag
      t.integer :price
      t.float :total_price
      t.integer :recycle_flg
      t.integer :syear
      t.integer :n_year_cd
      t.integer :new_flg
      t.string :e_distance
      t.string :distance
      t.string :inspection
      t.string :color_nm
      t.integer :color_cd2
      t.integer :n_fuel_cd
      t.string :navi_code
      t.string :img_url0
      t.string :img_url1
      t.string :img_url2
      t.string :img_url3
      t.string :img_url4
      t.string :img_url5
      t.string :img_url6
      t.string :img_url7
      t.string :img_url8
      t.string :img_url9
      t.string :img_url10
      t.string :img_url11
      t.string :img_url12
      t.string :img_url13
      t.string :img_url14
      t.string :img_url15
      t.string :img_url16
      t.string :img_url17
      t.string :img_url18
      t.string :img_url19
      t.string :img_text0
      t.string :img_text1
      t.string :img_text2
      t.string :img_text3
      t.string :img_text4
      t.string :img_text5
      t.string :img_text6
      t.string :img_text7
      t.string :img_text8
      t.string :img_text9
      t.string :img_text10
      t.string :img_text11
      t.string :img_text12
      t.string :img_text13
      t.string :img_text14
      t.string :img_text15
      t.string :img_text16
      t.string :img_text17
      t.string :img_text18
      t.string :img_text19
      t.integer :n_p_katashiki_id
      t.string :seibi
      t.integer :seibi_price_num
      t.string :repair_comment
      t.string :hosyou
      t.integer :hosyou_kikan_flg
      t.integer :hosyou_kikan_num
      t.string :p_hosyou_kikan
      t.integer :hosyou_kigen_flg
      t.string :hosyou_kigen_num
      t.integer :hosyou_kigen_no
      t.string :p_hosyou_kigen
      t.integer :hosyou_kyori_flg
      t.integer :hosyou_kyori_num
      t.string :p_hosyou_kyori
      t.string :assurance_comment
      t.integer :hosyou_flg
      t.date :kantei_date
      t.integer :kantei_syatai_id
      t.integer :kantei_naisou_id
      t.integer :kantei_kikan_id
      t.integer :kantei_kokkaku_id
      t.string :sub_photo_2
      t.string :sub_photo_4
      t.integer :option_values_2_0
      t.integer :option_values_2_1
      t.integer :option_values_2_2
      t.integer :option_values_2_3
      t.integer :option_values_2_4
      t.integer :option_values_2_5
      t.integer :option_values_2_6
      t.integer :option_values_2_7
      t.integer :option_values_2_8
      t.integer :option_values_2_9
      t.integer :option_values_2_10
      t.integer :option_values_2_11
      t.integer :option_values_2_12
      t.integer :option_values_2_13
      t.integer :option_values_2_14
      t.integer :option_values_2_15
      t.integer :option_values_2_16
      t.integer :option_values_2_17
      t.integer :option_values_2_18
      t.integer :option_values_2_19
      t.integer :option_values_2_20
      t.integer :option_values_2_21
      t.integer :option_values_2_22
      t.integer :option_values_2_23
      t.integer :option_values_2_24
      t.integer :option_values_2_25
      t.integer :option_values_2_26
      t.integer :option_values_2_27
      t.integer :option_values_2_28
      t.integer :option_values_2_29
      t.integer :option_values_2_30
      t.integer :option_values_2_31
      t.integer :option_values_2_32
      t.integer :option_values_2_33
      t.integer :option_values_2_34
      t.integer :option_values_2_35
      t.integer :option_values_2_36
      t.integer :option_values_2_37
      t.integer :option_values_2_38
      t.integer :option_values_2_39
      t.integer :option_values_2_40
      t.integer :option_values_2_41
      t.integer :option_values_2_42
      t.integer :option_values_2_43
      t.integer :option_values_2_44
      t.integer :option_values_2_45
      t.integer :option_values_2_46
      t.integer :option_values_2_47
      t.integer :option_values_2_48
      t.integer :option_values_2_49
      t.integer :option_values_2_50
      t.integer :option_values_2_51
      t.integer :option_values_2_52
      t.integer :option_values_2_53
      t.integer :option_values_2_54
      t.integer :option_values_2_55
      t.integer :option_values_2_56
      t.integer :option_values_2_57
      t.integer :option_values_2_58
      t.integer :option_values_2_59
      t.integer :option_values_web_0
      t.integer :option_values_web_1
      t.integer :option_values_web_2
      t.integer :option_values_web_3
      t.integer :option_values_web_4
      t.integer :option_values_web_5
      t.integer :option_values_web_6
      t.integer :option_values_web_7
      t.integer :option_values_web_8
      t.integer :option_values_web_9
      t.integer :option_values_web_10
      t.integer :option_values_web_11
      t.integer :option_values_web_12
      t.integer :option_values_web_13
      t.integer :option_values_web_14
      t.integer :option_values_web_15
      t.integer :option_values_web_16
      t.integer :option_values_web_17
      t.integer :option_values_web_18
      t.integer :option_values_web_19
      t.integer :option_values_web_20
      t.integer :option_values_web_21
      t.integer :option_values_web_22
      t.integer :option_values_web_23
      t.integer :option_values_web_24
      t.integer :option_values_web_25
      t.integer :option_values_web_26
      t.integer :option_values_web_27
      t.integer :option_values_web_28
      t.integer :option_values_web_29
      t.integer :option_values_web_30
      t.integer :option_values_web_31
      t.integer :option_values_web_32
      t.integer :option_values_web_33
      t.integer :option_values_web_34
      t.integer :option_values_web_35
      t.integer :option_values_web_36
      t.integer :option_values_web_37
      t.integer :option_values_web_38
      t.integer :option_values_web_39
      t.integer :option_values_web_40
      t.integer :option_values_web_41
      t.integer :option_values_web_42
      t.integer :option_values_web_43
      t.integer :option_values_web_44
      t.integer :option_values_web_45
      t.integer :option_values_web_46
      t.integer :option_values_web_47
      t.integer :option_values_web_48
      t.integer :option_values_web_49
      t.integer :option_values_web_50
      t.integer :option_values_web_51
      t.integer :option_values_web_52
      t.integer :option_values_web_53
      t.integer :option_values_web_54
      t.integer :option_values_web_55
      t.integer :option_values_web_56
      t.integer :option_values_web_57
      t.integer :option_values_web_58
      t.integer :option_values_web_59
      t.integer :option_values_1_0
      t.integer :option_values_1_1
      t.integer :option_values_1_2
      t.integer :option_values_1_3
      t.integer :option_values_1_4
      t.integer :option_values_1_5
      t.integer :option_values_1_6
      t.integer :option_values_1_7
      t.integer :option_values_1_8
      t.integer :option_values_1_9
      t.integer :option_values_1_10
      t.integer :option_values_1_11
      t.integer :option_values_1_12
      t.integer :option_values_1_13
      t.integer :option_values_1_14
      t.integer :option_values_1_15
      t.integer :option_values_1_16
      t.integer :option_values_1_17
      t.integer :option_values_1_18
      t.integer :option_values_1_19
      t.integer :option_values_1_20
      t.integer :option_values_1_21
      t.integer :option_values_1_22
      t.integer :option_values_1_23
      t.integer :option_values_1_24
      t.integer :option_values_1_25
      t.integer :option_values_1_26
      t.integer :option_values_1_27
      t.integer :option_values_1_28
      t.integer :option_values_1_29
      t.integer :option_values_1_30
      t.integer :option_values_1_31
      t.integer :option_values_1_32
      t.integer :option_values_1_33
      t.integer :option_values_1_34
      t.integer :option_values_1_35
      t.integer :option_values_1_36
      t.integer :option_values_1_37
      t.integer :option_values_1_38
      t.integer :option_values_1_39
      t.integer :option_values_1_40
      t.integer :option_values_1_41
      t.integer :option_values_1_42
      t.integer :option_values_1_43
      t.integer :option_values_1_44
      t.integer :option_values_1_45
      t.integer :option_values_1_46
      t.integer :option_values_1_47
      t.integer :option_values_1_48
      t.integer :option_values_1_49
      t.integer :option_values_1_50
      t.integer :option_values_1_51
      t.integer :option_values_1_52
      t.integer :option_values_1_53
      t.integer :option_values_1_54
      t.integer :option_values_1_55
      t.integer :option_values_1_56
      t.integer :option_values_1_57
      t.integer :option_values_1_58
      t.integer :option_values_1_59
      t.integer :option_values_1_60
      t.integer :option_values_1_61
      t.integer :option_values_1_62
      t.integer :option_values_1_63
      t.integer :option_values_1_64
      t.integer :keiro_id
      t.integer :goo_warranty
      t.integer :hosyou_item_count
      t.string :hosyou_item_comments
      t.integer :repair_upper_limit
      t.integer :repair_count
      t.integer :hosyou_limit_upper_limit
      t.string :hosyou_limit_comments
      t.integer :deductible
      t.string :deductible_comments
      t.string :hosyou_repair_receptionist
      t.integer :road_service
      t.integer :goo_plus_flg
      t.string :n_p_jititai_id

      t.timestamps null: false
    end
  end
end
