development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  database: db/goonet/development.mysql


production:
  url: <%= ENV['HEROKU_POSTGRESQL_IVORY_URL'] %>
  adapter: postgresql
  encoding: utf8
  pool: 5
  template: template0
  database: goonet_test_production
  username: goonet_test
  password: <%= ENV['GOONET_TEST_DATABASE_PASSWORD'] %>
