# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c4636302daf5a47f4040bf489e7985344de5476e38d84210a0dfbdd5c501c322a20ea04f7ff7bf6b825352f49f9a4253fb5c0ec2b21833f0c04a5a8644cff58

test:
  secret_key_base: d2cee8b99b4f4f5f3d5f50fcde62cec902916f3c0b569fc708e7487562b34a2a117f4b7c53cafc19b26d1d2a11859cb92651df00eca16093e57e44b4954efce2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
