# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2018031300002) do

  create_table "shops", force: :cascade do |t|
    t.string   "owner_cd",      limit: 255
    t.string   "owner_nm",      limit: 255
    t.string   "yubin",         limit: 255
    t.string   "owner_addr1",   limit: 255
    t.string   "owner_addr2",   limit: 255
    t.string   "tel",           limit: 255
    t.string   "phone_no",      limit: 255
    t.string   "fax",           limit: 255
    t.string   "shop_memo",     limit: 255
    t.string   "main_img",      limit: 255
    t.string   "detail_img_1",  limit: 255
    t.string   "detail_img_2",  limit: 255
    t.string   "detail_img_3",  limit: 255
    t.string   "detail_img_4",  limit: 255
    t.string   "detail_text_1", limit: 255
    t.string   "detail_text_2", limit: 255
    t.string   "detail_text_3", limit: 255
    t.string   "detail_text_4", limit: 255
    t.string   "shop_b_hour",   limit: 255
    t.string   "shop_reg_hol",  limit: 255
    t.string   "geo",           limit: 255
    t.string   "ido",           limit: 255
    t.string   "keido",         limit: 255
    t.datetime "created_at",                null: false
    t.datetime "updated_at",                null: false
  end

  create_table "zaikos", force: :cascade do |t|
    t.string   "stock_id",                   limit: 255
    t.string   "goocar_id",                  limit: 255
    t.string   "owner_cd",                   limit: 255
    t.string   "n_p_country_nm_n",           limit: 255
    t.integer  "n_country_cd",               limit: 4
    t.string   "brand_nm",                   limit: 255
    t.integer  "n_maker_cd",                 limit: 4
    t.string   "n_p_brand_nm_n",             limit: 255
    t.integer  "n_brand_cd",                 limit: 4
    t.string   "n_p_car_nm_n",               limit: 255
    t.integer  "n_car_cd",                   limit: 4
    t.string   "n_p_grade_nm_n",             limit: 255
    t.string   "grade_nm",                   limit: 255
    t.integer  "n_p_grade_id",               limit: 4
    t.string   "body_nm",                    limit: 255
    t.integer  "n_body_cd",                  limit: 4
    t.string   "exhaust_nm",                 limit: 255
    t.string   "n_p_door_n",                 limit: 255
    t.string   "fukabun",                    limit: 255
    t.integer  "repair_flag",                limit: 4
    t.integer  "price",                      limit: 4
    t.float    "total_price",                limit: 24
    t.integer  "recycle_flg",                limit: 4
    t.integer  "syear",                      limit: 4
    t.integer  "n_year_cd",                  limit: 4
    t.integer  "new_flg",                    limit: 4
    t.string   "e_distance",                 limit: 255
    t.string   "distance",                   limit: 255
    t.string   "inspection",                 limit: 255
    t.string   "color_nm",                   limit: 255
    t.integer  "color_cd2",                  limit: 4
    t.integer  "n_fuel_cd",                  limit: 4
    t.string   "navi_code",                  limit: 255
    t.string   "img_url0",                   limit: 255
    t.string   "img_url1",                   limit: 255
    t.string   "img_url2",                   limit: 255
    t.string   "img_url3",                   limit: 255
    t.string   "img_url4",                   limit: 255
    t.string   "img_url5",                   limit: 255
    t.string   "img_url6",                   limit: 255
    t.string   "img_url7",                   limit: 255
    t.string   "img_url8",                   limit: 255
    t.string   "img_url9",                   limit: 255
    t.string   "img_url10",                  limit: 255
    t.string   "img_url11",                  limit: 255
    t.string   "img_url12",                  limit: 255
    t.string   "img_url13",                  limit: 255
    t.string   "img_url14",                  limit: 255
    t.string   "img_url15",                  limit: 255
    t.string   "img_url16",                  limit: 255
    t.string   "img_url17",                  limit: 255
    t.string   "img_url18",                  limit: 255
    t.string   "img_url19",                  limit: 255
    t.string   "img_text0",                  limit: 255
    t.string   "img_text1",                  limit: 255
    t.string   "img_text2",                  limit: 255
    t.string   "img_text3",                  limit: 255
    t.string   "img_text4",                  limit: 255
    t.string   "img_text5",                  limit: 255
    t.string   "img_text6",                  limit: 255
    t.string   "img_text7",                  limit: 255
    t.string   "img_text8",                  limit: 255
    t.string   "img_text9",                  limit: 255
    t.string   "img_text10",                 limit: 255
    t.string   "img_text11",                 limit: 255
    t.string   "img_text12",                 limit: 255
    t.string   "img_text13",                 limit: 255
    t.string   "img_text14",                 limit: 255
    t.string   "img_text15",                 limit: 255
    t.string   "img_text16",                 limit: 255
    t.string   "img_text17",                 limit: 255
    t.string   "img_text18",                 limit: 255
    t.string   "img_text19",                 limit: 255
    t.integer  "n_p_katashiki_id",           limit: 4
    t.string   "seibi",                      limit: 255
    t.integer  "seibi_price_num",            limit: 4
    t.string   "repair_comment",             limit: 255
    t.string   "hosyou",                     limit: 255
    t.integer  "hosyou_kikan_flg",           limit: 4
    t.integer  "hosyou_kikan_num",           limit: 4
    t.string   "p_hosyou_kikan",             limit: 255
    t.integer  "hosyou_kigen_flg",           limit: 4
    t.string   "hosyou_kigen_num",           limit: 255
    t.integer  "hosyou_kigen_no",            limit: 4
    t.string   "p_hosyou_kigen",             limit: 255
    t.integer  "hosyou_kyori_flg",           limit: 4
    t.integer  "hosyou_kyori_num",           limit: 4
    t.string   "p_hosyou_kyori",             limit: 255
    t.string   "assurance_comment",          limit: 255
    t.integer  "hosyou_flg",                 limit: 4
    t.date     "kantei_date"
    t.integer  "kantei_syatai_id",           limit: 4
    t.integer  "kantei_naisou_id",           limit: 4
    t.integer  "kantei_kikan_id",            limit: 4
    t.integer  "kantei_kokkaku_id",          limit: 4
    t.string   "sub_photo_2",                limit: 255
    t.string   "sub_photo_4",                limit: 255
    t.integer  "option_values_2_0",          limit: 4
    t.integer  "option_values_2_1",          limit: 4
    t.integer  "option_values_2_2",          limit: 4
    t.integer  "option_values_2_3",          limit: 4
    t.integer  "option_values_2_4",          limit: 4
    t.integer  "option_values_2_5",          limit: 4
    t.integer  "option_values_2_6",          limit: 4
    t.integer  "option_values_2_7",          limit: 4
    t.integer  "option_values_2_8",          limit: 4
    t.integer  "option_values_2_9",          limit: 4
    t.integer  "option_values_2_10",         limit: 4
    t.integer  "option_values_2_11",         limit: 4
    t.integer  "option_values_2_12",         limit: 4
    t.integer  "option_values_2_13",         limit: 4
    t.integer  "option_values_2_14",         limit: 4
    t.integer  "option_values_2_15",         limit: 4
    t.integer  "option_values_2_16",         limit: 4
    t.integer  "option_values_2_17",         limit: 4
    t.integer  "option_values_2_18",         limit: 4
    t.integer  "option_values_2_19",         limit: 4
    t.integer  "option_values_2_20",         limit: 4
    t.integer  "option_values_2_21",         limit: 4
    t.integer  "option_values_2_22",         limit: 4
    t.integer  "option_values_2_23",         limit: 4
    t.integer  "option_values_2_24",         limit: 4
    t.integer  "option_values_2_25",         limit: 4
    t.integer  "option_values_2_26",         limit: 4
    t.integer  "option_values_2_27",         limit: 4
    t.integer  "option_values_2_28",         limit: 4
    t.integer  "option_values_2_29",         limit: 4
    t.integer  "option_values_2_30",         limit: 4
    t.integer  "option_values_2_31",         limit: 4
    t.integer  "option_values_2_32",         limit: 4
    t.integer  "option_values_2_33",         limit: 4
    t.integer  "option_values_2_34",         limit: 4
    t.integer  "option_values_2_35",         limit: 4
    t.integer  "option_values_2_36",         limit: 4
    t.integer  "option_values_2_37",         limit: 4
    t.integer  "option_values_2_38",         limit: 4
    t.integer  "option_values_2_39",         limit: 4
    t.integer  "option_values_2_40",         limit: 4
    t.integer  "option_values_2_41",         limit: 4
    t.integer  "option_values_2_42",         limit: 4
    t.integer  "option_values_2_43",         limit: 4
    t.integer  "option_values_2_44",         limit: 4
    t.integer  "option_values_2_45",         limit: 4
    t.integer  "option_values_2_46",         limit: 4
    t.integer  "option_values_2_47",         limit: 4
    t.integer  "option_values_2_48",         limit: 4
    t.integer  "option_values_2_49",         limit: 4
    t.integer  "option_values_2_50",         limit: 4
    t.integer  "option_values_2_51",         limit: 4
    t.integer  "option_values_2_52",         limit: 4
    t.integer  "option_values_2_53",         limit: 4
    t.integer  "option_values_2_54",         limit: 4
    t.integer  "option_values_2_55",         limit: 4
    t.integer  "option_values_2_56",         limit: 4
    t.integer  "option_values_2_57",         limit: 4
    t.integer  "option_values_2_58",         limit: 4
    t.integer  "option_values_2_59",         limit: 4
    t.integer  "option_values_web_0",        limit: 4
    t.integer  "option_values_web_1",        limit: 4
    t.integer  "option_values_web_2",        limit: 4
    t.integer  "option_values_web_3",        limit: 4
    t.integer  "option_values_web_4",        limit: 4
    t.integer  "option_values_web_5",        limit: 4
    t.integer  "option_values_web_6",        limit: 4
    t.integer  "option_values_web_7",        limit: 4
    t.integer  "option_values_web_8",        limit: 4
    t.integer  "option_values_web_9",        limit: 4
    t.integer  "option_values_web_10",       limit: 4
    t.integer  "option_values_web_11",       limit: 4
    t.integer  "option_values_web_12",       limit: 4
    t.integer  "option_values_web_13",       limit: 4
    t.integer  "option_values_web_14",       limit: 4
    t.integer  "option_values_web_15",       limit: 4
    t.integer  "option_values_web_16",       limit: 4
    t.integer  "option_values_web_17",       limit: 4
    t.integer  "option_values_web_18",       limit: 4
    t.integer  "option_values_web_19",       limit: 4
    t.integer  "option_values_web_20",       limit: 4
    t.integer  "option_values_web_21",       limit: 4
    t.integer  "option_values_web_22",       limit: 4
    t.integer  "option_values_web_23",       limit: 4
    t.integer  "option_values_web_24",       limit: 4
    t.integer  "option_values_web_25",       limit: 4
    t.integer  "option_values_web_26",       limit: 4
    t.integer  "option_values_web_27",       limit: 4
    t.integer  "option_values_web_28",       limit: 4
    t.integer  "option_values_web_29",       limit: 4
    t.integer  "option_values_web_30",       limit: 4
    t.integer  "option_values_web_31",       limit: 4
    t.integer  "option_values_web_32",       limit: 4
    t.integer  "option_values_web_33",       limit: 4
    t.integer  "option_values_web_34",       limit: 4
    t.integer  "option_values_web_35",       limit: 4
    t.integer  "option_values_web_36",       limit: 4
    t.integer  "option_values_web_37",       limit: 4
    t.integer  "option_values_web_38",       limit: 4
    t.integer  "option_values_web_39",       limit: 4
    t.integer  "option_values_web_40",       limit: 4
    t.integer  "option_values_web_41",       limit: 4
    t.integer  "option_values_web_42",       limit: 4
    t.integer  "option_values_web_43",       limit: 4
    t.integer  "option_values_web_44",       limit: 4
    t.integer  "option_values_web_45",       limit: 4
    t.integer  "option_values_web_46",       limit: 4
    t.integer  "option_values_web_47",       limit: 4
    t.integer  "option_values_web_48",       limit: 4
    t.integer  "option_values_web_49",       limit: 4
    t.integer  "option_values_web_50",       limit: 4
    t.integer  "option_values_web_51",       limit: 4
    t.integer  "option_values_web_52",       limit: 4
    t.integer  "option_values_web_53",       limit: 4
    t.integer  "option_values_web_54",       limit: 4
    t.integer  "option_values_web_55",       limit: 4
    t.integer  "option_values_web_56",       limit: 4
    t.integer  "option_values_web_57",       limit: 4
    t.integer  "option_values_web_58",       limit: 4
    t.integer  "option_values_web_59",       limit: 4
    t.integer  "option_values_1_0",          limit: 4
    t.integer  "option_values_1_1",          limit: 4
    t.integer  "option_values_1_2",          limit: 4
    t.integer  "option_values_1_3",          limit: 4
    t.integer  "option_values_1_4",          limit: 4
    t.integer  "option_values_1_5",          limit: 4
    t.integer  "option_values_1_6",          limit: 4
    t.integer  "option_values_1_7",          limit: 4
    t.integer  "option_values_1_8",          limit: 4
    t.integer  "option_values_1_9",          limit: 4
    t.integer  "option_values_1_10",         limit: 4
    t.integer  "option_values_1_11",         limit: 4
    t.integer  "option_values_1_12",         limit: 4
    t.integer  "option_values_1_13",         limit: 4
    t.integer  "option_values_1_14",         limit: 4
    t.integer  "option_values_1_15",         limit: 4
    t.integer  "option_values_1_16",         limit: 4
    t.integer  "option_values_1_17",         limit: 4
    t.integer  "option_values_1_18",         limit: 4
    t.integer  "option_values_1_19",         limit: 4
    t.integer  "option_values_1_20",         limit: 4
    t.integer  "option_values_1_21",         limit: 4
    t.integer  "option_values_1_22",         limit: 4
    t.integer  "option_values_1_23",         limit: 4
    t.integer  "option_values_1_24",         limit: 4
    t.integer  "option_values_1_25",         limit: 4
    t.integer  "option_values_1_26",         limit: 4
    t.integer  "option_values_1_27",         limit: 4
    t.integer  "option_values_1_28",         limit: 4
    t.integer  "option_values_1_29",         limit: 4
    t.integer  "option_values_1_30",         limit: 4
    t.integer  "option_values_1_31",         limit: 4
    t.integer  "option_values_1_32",         limit: 4
    t.integer  "option_values_1_33",         limit: 4
    t.integer  "option_values_1_34",         limit: 4
    t.integer  "option_values_1_35",         limit: 4
    t.integer  "option_values_1_36",         limit: 4
    t.integer  "option_values_1_37",         limit: 4
    t.integer  "option_values_1_38",         limit: 4
    t.integer  "option_values_1_39",         limit: 4
    t.integer  "option_values_1_40",         limit: 4
    t.integer  "option_values_1_41",         limit: 4
    t.integer  "option_values_1_42",         limit: 4
    t.integer  "option_values_1_43",         limit: 4
    t.integer  "option_values_1_44",         limit: 4
    t.integer  "option_values_1_45",         limit: 4
    t.integer  "option_values_1_46",         limit: 4
    t.integer  "option_values_1_47",         limit: 4
    t.integer  "option_values_1_48",         limit: 4
    t.integer  "option_values_1_49",         limit: 4
    t.integer  "option_values_1_50",         limit: 4
    t.integer  "option_values_1_51",         limit: 4
    t.integer  "option_values_1_52",         limit: 4
    t.integer  "option_values_1_53",         limit: 4
    t.integer  "option_values_1_54",         limit: 4
    t.integer  "option_values_1_55",         limit: 4
    t.integer  "option_values_1_56",         limit: 4
    t.integer  "option_values_1_57",         limit: 4
    t.integer  "option_values_1_58",         limit: 4
    t.integer  "option_values_1_59",         limit: 4
    t.integer  "option_values_1_60",         limit: 4
    t.integer  "option_values_1_61",         limit: 4
    t.integer  "option_values_1_62",         limit: 4
    t.integer  "option_values_1_63",         limit: 4
    t.integer  "option_values_1_64",         limit: 4
    t.integer  "keiro_id",                   limit: 4
    t.integer  "goo_warranty",               limit: 4
    t.integer  "hosyou_item_count",          limit: 4
    t.string   "hosyou_item_comments",       limit: 255
    t.integer  "repair_upper_limit",         limit: 4
    t.integer  "repair_count",               limit: 4
    t.integer  "hosyou_limit_upper_limit",   limit: 4
    t.string   "hosyou_limit_comments",      limit: 255
    t.integer  "deductible",                 limit: 4
    t.string   "deductible_comments",        limit: 255
    t.string   "hosyou_repair_receptionist", limit: 255
    t.integer  "road_service",               limit: 4
    t.integer  "goo_plus_flg",               limit: 4
    t.string   "n_p_jititai_id",             limit: 255
    t.datetime "created_at",                             null: false
    t.datetime "updated_at",                             null: false
  end

end
